name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

<<<<<<< HEAD
      - name: Verificar e Inyectar API Key
=======
      - name: Inyectar API Key
        - name: Verificar y Modificar Archivo
>>>>>>> 2df910394fd45930adf1bd43dd3532b929f8bde2
        run: |
          echo "Listando archivos para verificar ruta:"
          ls -R
          
          # Verificamos si el archivo existe antes de aplicar sed
          if [ -f "js/camera.js" ]; then
            echo "Archivo encontrado. Inyectando clave..."
            sed -i "s/REPLACE_ME_WITH_KEY/${{ secrets.IMGBB_API_KEY }}/g" js/camera.js
            echo "✅ Clave inyectada."
          else
            echo "❌ ERROR: No se encontró el archivo en js/camera.js"
            exit 1
          fi

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
<<<<<<< HEAD
          folder: . 
          branch: gh-pages
=======
          folder: . # La carpeta donde está tu index.html
          branch: gh-pages # Se publicará en esta rama
>>>>>>> 2df910394fd45930adf1bd43dd3532b929f8bde2
